<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'name' => 'Pengaturan',
                'url' => '/settings',
                'component' => 'Settings',
                'modules' => '#',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-settings',
                'order' => 5,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-03-02 09:29:01',
                'updated_at' => '2020-07-28 08:16:30',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 1,
                'name' => 'Pengguna',
                'url' => '/settings/users',
                'component' => 'User,UserCreate,UserUpdate:id',
                'modules' => 'user',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-user',
                'order' => 1,
                'function' => 'R,C,D,A,S,E,I,U',
                'status' => 1,
                'created_at' => '2020-03-02 09:30:06',
                'updated_at' => '2020-06-29 20:25:22',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 1,
                'name' => 'Menu',
                'url' => '/settings/menus',
                'component' => 'Menu,MenuCreate,MenuUpdate:id',
                'modules' => 'menu',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-grid',
                'order' => 3,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-02 09:30:25',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 0,
                'name' => 'Data Master',
                'url' => '/master',
                'component' => 'Master',
                'modules' => '#',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-layers',
                'order' => 6,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-02 20:37:55',
                'updated_at' => '2020-07-28 08:16:30',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 10,
                'parent_id' => 0,
                'name' => 'Beranda',
                'url' => '/home',
                'component' => 'Home',
                'modules' => 'home',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-home',
                'order' => 1,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-06 19:31:19',
                'updated_at' => '2020-06-29 20:20:55',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 12,
                'parent_id' => 1,
                'name' => 'Hak Akses',
                'url' => '/settings/role',
                'component' => 'Role,RoleCreate,RoleUpdate:id',
                'modules' => 'role',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-shuffle',
                'order' => 2,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-08 11:19:56',
                'updated_at' => '2020-06-29 20:27:08',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 14,
                'parent_id' => 4,
                'name' => 'Tipe Surat',
                'url' => '/master/types',
                'component' => 'Type',
                'modules' => 'type',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-direction',
                'order' => 1,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-12 10:46:22',
                'updated_at' => '2020-06-29 20:28:40',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 15,
                'parent_id' => 4,
                'name' => 'Klasifikasi Surat',
                'url' => '/master/classifications',
                'component' => 'Classification',
                'modules' => 'classification',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-fire',
                'order' => 3,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-12 10:47:14',
                'updated_at' => '2020-06-29 20:29:46',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 16,
                'parent_id' => 4,
                'name' => 'Kategori Disposisi',
                'url' => '/master/class-dispositions',
                'component' => 'ClassDisposition',
                'modules' => 'class_disposition',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-screen-tablet',
                'order' => 4,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-12 10:48:05',
                'updated_at' => '2020-06-29 20:30:30',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 17,
                'parent_id' => 4,
                'name' => 'Template Surat',
                'url' => '/master/template',
                'component' => 'Template,TemplateCreate,TemplateUpdate:id',
                'modules' => 'template',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-social-dropbox',
                'order' => 5,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-12 10:48:42',
                'updated_at' => '2020-06-29 20:30:43',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 18,
                'parent_id' => 4,
                'name' => 'Jenis Nota Dinas',
                'url' => '/master/type-notes',
                'component' => 'TypeNote',
                'modules' => 'type_notes',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-notebook',
                'order' => 2,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-13 10:59:59',
                'updated_at' => '2020-06-29 20:29:31',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 19,
                'parent_id' => 1,
                'name' => 'Pengaturan Lanjutan',
                'url' => '/settings/setting',
                'component' => 'Setting,SettingCreate,SettingUpdate:id',
                'modules' => 'setting',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-wrench',
                'order' => 4,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-03-21 10:59:47',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 20,
                'parent_id' => 23,
                'name' => 'Data Surat Keluar',
                'url' => '/outgoing-mails',
                'component' => 'OutgoingMail,OutgoingMailCreate,OutgoingMailUpdate:id',
                'modules' => 'outgoing-mails',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope-open',
                'order' => 1,
                'function' => 'R,C,U,D,A,S,E,I',
                'status' => 1,
                'created_at' => '2020-03-23 20:07:08',
                'updated_at' => '2020-07-12 13:16:57',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 21,
                'parent_id' => 1,
                'name' => 'Jenjang Persetujuan Surat Direksi',
                'url' => '/settings/reviews',
                'component' => 'Review,ReviewUpdate:id',
                'modules' => 'reviews',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-eye',
                'order' => 5,
                'function' => 'R,U,C,D',
                'status' => 1,
                'created_at' => '2020-03-30 15:14:48',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 22,
                'parent_id' => 1,
                'name' => 'Tanda Tangan Digital',
                'url' => '/settings/digital-signatures',
                'component' => 'DigitalSignature,DigitalSignatureCreate,DigitalSignatureUpdate:id',
                'modules' => 'digital-signatures',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-umbrella',
                'order' => 6,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-04-02 06:02:47',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 23,
                'parent_id' => 0,
                'name' => 'Surat Keluar',
                'url' => '/outgoings',
                'component' => 'Root',
                'modules' => '#',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope-letter',
                'order' => 3,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-04-17 16:35:40',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 24,
                'parent_id' => 23,
                'name' => 'Persetujuan',
                'url' => '/outgoing-mails-approval',
                'component' => 'Approval,ApprovalUpdate:id',
                'modules' => 'outgoing-mails-approval',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-check',
                'order' => 2,
                'function' => 'A,R,U',
                'status' => 1,
                'created_at' => '2020-04-17 16:41:31',
                'updated_at' => '2020-06-29 20:24:11',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 25,
                'parent_id' => 23,
                'name' => 'Penandatanganan',
                'url' => '/outgoing-mails-signed',
                'component' => 'Signed,SignedUpdate:id',
                'modules' => 'outgoing-mails-signed',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-key',
                'order' => 3,
                'function' => 'R,U,A',
                'status' => 1,
                'created_at' => '2020-04-17 16:44:25',
                'updated_at' => '2020-06-29 20:24:33',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 26,
                'parent_id' => 23,
                'name' => 'Penerbitan Surat',
                'url' => '/outgoing-mails-admin',
                'component' => 'Publish,PublishUpdate:id',
                'modules' => 'outgoing-mails-admin',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-paper-plane',
                'order' => 4,
                'function' => 'R,U,A,E',
                'status' => 1,
                'created_at' => '2020-04-17 16:46:42',
                'updated_at' => '2020-06-29 20:24:55',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'parent_id' => 0,
                'name' => 'Surat Masuk',
                'url' => 'incomings',
                'component' => 'Root',
                'modules' => '#',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope',
                'order' => 2,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-04-24 15:00:52',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'parent_id' => 27,
                'name' => 'Data Surat Masuk',
                'url' => '/incoming-mails',
                'component' => 'IncomingMail,IncomingMailCreate,IncomingMailUpdate:id,IncomingMailFollow-Up:id',
                'modules' => 'incoming-mails',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope',
                'order' => 1,
                'function' => 'R,U,C,D,E,I,S',
                'status' => 1,
                'created_at' => '2020-04-24 15:03:29',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'parent_id' => 27,
                'name' => 'Disposisi',
                'url' => '/incoming-mails-disposition',
                'component' => 'Disposition,DispositionCreate,DispositionUpdate:id',
                'modules' => 'dispositions',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-cursor',
                'order' => 2,
                'function' => 'R,U,C,D',
                'status' => 1,
                'created_at' => '2020-04-24 15:05:09',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 30,
                'parent_id' => 27,
                'name' => 'Tindak Lanjut Disposisi',
                'url' => '/dispositions-follow',
                'component' => 'DispositionFollowUp,DispositionFollowUpUpdate:id',
                'modules' => 'dispositions-follow',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-pin',
                'order' => 3,
                'function' => 'R,U,C',
                'status' => 1,
                'created_at' => '2020-04-30 20:00:55',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'parent_id' => 1,
                'name' => 'Pemetaan Struktur',
                'url' => '/setting/mapping-structure',
                'component' => 'MappingStructure,MappingStructureUpdate:id',
                'modules' => 'mapping-structure',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-badge',
                'order' => 7,
                'function' => 'R,U',
                'status' => 1,
                'created_at' => '2020-05-08 06:41:44',
                'updated_at' => '2020-07-12 13:18:54',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 33,
                'parent_id' => 0,
                'name' => 'Laporan',
                'url' => '/report',
                'component' => 'Root',
                'modules' => 'report',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-notebook',
                'order' => 7,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-05-30 16:45:56',
                'updated_at' => '2020-07-28 08:16:30',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 34,
                'parent_id' => 33,
                'name' => 'Laporan Surat Masuk',
                'url' => '/reports/incoming',
                'component' => 'ReportIncomingMail',
                'modules' => 'report-incoming',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope',
                'order' => 1,
                'function' => 'R,E',
                'status' => 1,
                'created_at' => '2020-05-30 16:47:46',
                'updated_at' => '2020-07-12 13:16:57',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 35,
                'parent_id' => 33,
                'name' => 'Laporan Surat Keluar',
                'url' => '/reports/outgoing',
                'component' => 'ReportOutgoingMail',
                'modules' => 'report-outgoing',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope-open',
                'order' => 2,
                'function' => 'R,E',
                'status' => 1,
                'created_at' => '2020-05-30 16:50:25',
                'updated_at' => '2020-07-12 13:16:57',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 36,
                'parent_id' => 33,
                'name' => 'Laporan Disposisi',
                'url' => '/reports/disposition',
                'component' => 'ReportDisposition',
                'modules' => 'report-disposition',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-cursor',
                'order' => 3,
                'function' => 'R,E',
                'status' => 1,
                'created_at' => '2020-05-30 16:51:55',
                'updated_at' => '2020-07-12 13:16:57',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 37,
                'parent_id' => 1,
                'name' => 'Pemetaan Tindak Lanjut',
                'url' => '/settings/mapping-follow-outgoing',
                'component' => 'MappingFollowOutgoing',
                'modules' => 'mapping-follow-outgoing',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-share-alt',
                'order' => 8,
                'function' => 'R,C,D',
                'status' => 1,
                'created_at' => '2020-07-12 13:21:16',
                'updated_at' => '2020-07-12 13:27:53',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 38,
                'parent_id' => 23,
                'name' => 'Tindak Lanjut',
                'url' => '/outgoing-mail-follow',
                'component' => 'OutgoingFollowUp,OutgoingFollowUpUpdate:id',
                'modules' => 'outgoing-mails-follow',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-pin',
                'order' => 5,
                'function' => 'R,C,D',
                'status' => 1,
                'created_at' => '2020-07-12 13:24:29',
                'updated_at' => '2020-07-12 13:27:53',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 39,
                'parent_id' => 1,
                'name' => 'Sinkronisasi',
                'url' => '/settings/syncs',
                'component' => 'Sync',
                'modules' => 'syncs',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-refresh',
                'order' => 9,
                'function' => 'R,C,U,D',
                'status' => 1,
                'created_at' => '2020-07-15 22:06:06',
                'updated_at' => '2020-07-28 08:16:30',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 40,
                'parent_id' => 0,
                'name' => 'Arsip',
                'url' => '/archives',
                'component' => 'Root',
                'modules' => 'archives',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-drawer',
                'order' => 4,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-07-28 08:16:03',
                'updated_at' => '2020-07-28 08:19:20',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 41,
                'parent_id' => 40,
                'name' => 'Arsip Surat Keluar',
                'url' => '/archives-outgoing',
                'component' => 'ArchiveOutgoing,ArchiveOutgoingDetail:id',
                'modules' => 'archive-outgoings',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope-letter',
                'order' => 33,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-07-28 08:17:25',
                'updated_at' => '2020-07-28 08:17:25',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 42,
                'parent_id' => 40,
                'name' => 'Arsip Surat Masuk',
                'url' => '/archives-incoming',
                'component' => 'ArchiveIncoming,ArchiveIncomingDetail:id',
                'modules' => 'archive-incomings',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-envelope',
                'order' => 34,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-07-28 08:18:15',
                'updated_at' => '2020-07-28 08:18:15',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 43,
                'parent_id' => 40,
                'name' => 'Arsip Disposisi',
                'url' => '/archives-disposition',
                'component' => 'ArchiveDisposition,ArchiveDispositionDetail:id',
                'modules' => 'archive-dispositions',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-cursor',
                'order' => 35,
                'function' => 'R',
                'status' => 1,
                'created_at' => '2020-07-28 08:19:02',
                'updated_at' => '2020-07-28 08:19:02',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 44,
                'parent_id' => 1,
                'name' => 'Divisi Spesial Surat Keluar',
                'url' => '/special-division-outgoing',
                'component' => 'SpecialDivisionOutgoing',
                'modules' => 'special-division-outgoing',
                'show' => 0,
                'categories' => 'web',
                'icon' => 'icon-disc',
                'order' => 36,
                'function' => 'R,C,D',
                'status' => 1,
                'created_at' => '2020-07-31 21:56:38',
                'updated_at' => '2020-07-31 21:56:38',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}