<?php

use Illuminate\Database\Seeder;

class MenuRolesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_roles')->delete();
        
        \DB::table('menu_roles')->insert(array (
            0 => 
            array (
                'menu_id' => 1,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-11 07:22:01',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            1 => 
            array (
                'menu_id' => 1,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            2 => 
            array (
                'menu_id' => 2,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-03-09 20:41:09',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            3 => 
            array (
                'menu_id' => 2,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            4 => 
            array (
                'menu_id' => 3,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-09 20:41:09',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            5 => 
            array (
                'menu_id' => 3,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 06:35:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            6 => 
            array (
                'menu_id' => 4,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-11 07:22:01',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            7 => 
            array (
                'menu_id' => 4,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            8 => 
            array (
                'menu_id' => 10,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-09 20:41:09',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            9 => 
            array (
                'menu_id' => 10,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            10 => 
            array (
                'menu_id' => 10,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            11 => 
            array (
                'menu_id' => 10,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            12 => 
            array (
                'menu_id' => 10,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            13 => 
            array (
                'menu_id' => 10,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            14 => 
            array (
                'menu_id' => 10,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            15 => 
            array (
                'menu_id' => 12,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-11 07:22:01',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            16 => 
            array (
                'menu_id' => 12,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            17 => 
            array (
                'menu_id' => 14,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            18 => 
            array (
                'menu_id' => 14,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            19 => 
            array (
                'menu_id' => 15,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            20 => 
            array (
                'menu_id' => 15,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            21 => 
            array (
                'menu_id' => 16,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            22 => 
            array (
                'menu_id' => 16,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            23 => 
            array (
                'menu_id' => 17,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            24 => 
            array (
                'menu_id' => 17,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            25 => 
            array (
                'menu_id' => 18,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            26 => 
            array (
                'menu_id' => 18,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-13 11:00:15',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            27 => 
            array (
                'menu_id' => 19,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            28 => 
            array (
                'menu_id' => 19,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-21 11:00:09',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            29 => 
            array (
                'menu_id' => 20,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            30 => 
            array (
                'menu_id' => 20,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-03-23 20:07:31',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            31 => 
            array (
                'menu_id' => 20,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            32 => 
            array (
                'menu_id' => 20,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            33 => 
            array (
                'menu_id' => 20,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            34 => 
            array (
                'menu_id' => 20,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            35 => 
            array (
                'menu_id' => 20,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            36 => 
            array (
                'menu_id' => 21,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            37 => 
            array (
                'menu_id' => 21,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-30 15:15:11',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            38 => 
            array (
                'menu_id' => 22,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            39 => 
            array (
                'menu_id' => 22,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-02 06:17:56',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            40 => 
            array (
                'menu_id' => 23,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            41 => 
            array (
                'menu_id' => 23,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            42 => 
            array (
                'menu_id' => 23,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            43 => 
            array (
                'menu_id' => 23,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            44 => 
            array (
                'menu_id' => 23,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            45 => 
            array (
                'menu_id' => 23,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            46 => 
            array (
                'menu_id' => 23,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            47 => 
            array (
                'menu_id' => 24,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            48 => 
            array (
                'menu_id' => 24,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            49 => 
            array (
                'menu_id' => 24,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            50 => 
            array (
                'menu_id' => 24,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            51 => 
            array (
                'menu_id' => 24,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            52 => 
            array (
                'menu_id' => 24,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            53 => 
            array (
                'menu_id' => 25,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            54 => 
            array (
                'menu_id' => 25,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            55 => 
            array (
                'menu_id' => 25,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-13 14:59:35',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            56 => 
            array (
                'menu_id' => 25,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-08-23 15:09:04',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            57 => 
            array (
                'menu_id' => 25,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            58 => 
            array (
                'menu_id' => 26,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            59 => 
            array (
                'menu_id' => 26,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            60 => 
            array (
                'menu_id' => 26,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            61 => 
            array (
                'menu_id' => 27,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            62 => 
            array (
                'menu_id' => 27,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 15:05:48',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            63 => 
            array (
                'menu_id' => 27,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:48:36',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            64 => 
            array (
                'menu_id' => 27,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            65 => 
            array (
                'menu_id' => 27,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            66 => 
            array (
                'menu_id' => 27,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            67 => 
            array (
                'menu_id' => 27,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            68 => 
            array (
                'menu_id' => 28,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            69 => 
            array (
                'menu_id' => 28,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 15:05:49',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            70 => 
            array (
                'menu_id' => 28,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:48:36',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            71 => 
            array (
                'menu_id' => 28,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            72 => 
            array (
                'menu_id' => 28,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            73 => 
            array (
                'menu_id' => 28,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            74 => 
            array (
                'menu_id' => 28,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            75 => 
            array (
                'menu_id' => 29,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            76 => 
            array (
                'menu_id' => 29,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 15:05:49',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            77 => 
            array (
                'menu_id' => 29,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            78 => 
            array (
                'menu_id' => 29,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            79 => 
            array (
                'menu_id' => 29,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            80 => 
            array (
                'menu_id' => 29,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            81 => 
            array (
                'menu_id' => 30,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            82 => 
            array (
                'menu_id' => 30,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-05 16:35:38',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            83 => 
            array (
                'menu_id' => 30,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            84 => 
            array (
                'menu_id' => 30,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            85 => 
            array (
                'menu_id' => 30,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            86 => 
            array (
                'menu_id' => 30,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            87 => 
            array (
                'menu_id' => 31,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            88 => 
            array (
                'menu_id' => 31,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-08 06:42:02',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            89 => 
            array (
                'menu_id' => 33,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            90 => 
            array (
                'menu_id' => 33,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            91 => 
            array (
                'menu_id' => 33,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            92 => 
            array (
                'menu_id' => 33,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            93 => 
            array (
                'menu_id' => 33,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            94 => 
            array (
                'menu_id' => 33,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            95 => 
            array (
                'menu_id' => 33,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            96 => 
            array (
                'menu_id' => 34,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            97 => 
            array (
                'menu_id' => 34,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            98 => 
            array (
                'menu_id' => 34,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:48:36',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            99 => 
            array (
                'menu_id' => 34,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            100 => 
            array (
                'menu_id' => 34,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            101 => 
            array (
                'menu_id' => 35,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            102 => 
            array (
                'menu_id' => 35,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            103 => 
            array (
                'menu_id' => 35,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            104 => 
            array (
                'menu_id' => 35,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            105 => 
            array (
                'menu_id' => 35,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            106 => 
            array (
                'menu_id' => 35,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            107 => 
            array (
                'menu_id' => 35,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            108 => 
            array (
                'menu_id' => 36,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            109 => 
            array (
                'menu_id' => 36,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            110 => 
            array (
                'menu_id' => 36,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            111 => 
            array (
                'menu_id' => 36,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            112 => 
            array (
                'menu_id' => 36,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            113 => 
            array (
                'menu_id' => 36,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            114 => 
            array (
                'menu_id' => 37,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            115 => 
            array (
                'menu_id' => 37,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-12 13:25:21',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            116 => 
            array (
                'menu_id' => 38,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            117 => 
            array (
                'menu_id' => 38,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-12 13:25:21',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            118 => 
            array (
                'menu_id' => 38,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:39:51',
                'updated_at' => '2020-10-04 11:39:51',
            ),
            119 => 
            array (
                'menu_id' => 38,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-08-14 11:23:48',
                'updated_at' => '2020-10-04 11:39:33',
            ),
            120 => 
            array (
                'menu_id' => 38,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:39:22',
                'updated_at' => '2020-10-04 11:39:22',
            ),
            121 => 
            array (
                'menu_id' => 38,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:50',
                'updated_at' => '2020-10-04 11:38:50',
            ),
            122 => 
            array (
                'menu_id' => 39,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            123 => 
            array (
                'menu_id' => 39,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-15 22:06:34',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            124 => 
            array (
                'menu_id' => 40,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            125 => 
            array (
                'menu_id' => 40,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-28 08:20:07',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            126 => 
            array (
                'menu_id' => 41,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            127 => 
            array (
                'menu_id' => 41,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-28 08:20:07',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            128 => 
            array (
                'menu_id' => 42,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            129 => 
            array (
                'menu_id' => 42,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-28 08:20:07',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            130 => 
            array (
                'menu_id' => 43,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            131 => 
            array (
                'menu_id' => 43,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-28 08:20:07',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            132 => 
            array (
                'menu_id' => 44,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            133 => 
            array (
                'menu_id' => 44,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-31 21:57:28',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            134 => 
            array (
                'menu_id' => 45,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            135 => 
            array (
                'menu_id' => 45,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:35:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            136 => 
            array (
                'menu_id' => 46,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            137 => 
            array (
                'menu_id' => 46,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:35:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            138 => 
            array (
                'menu_id' => 47,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            139 => 
            array (
                'menu_id' => 47,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:35:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            140 => 
            array (
                'menu_id' => 48,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            141 => 
            array (
                'menu_id' => 48,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:35:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
            142 => 
            array (
                'menu_id' => 49,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:38:21',
                'updated_at' => '2020-10-04 11:38:21',
            ),
            143 => 
            array (
                'menu_id' => 49,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-10-04 11:35:08',
                'updated_at' => '2020-10-04 11:35:08',
            ),
        ));
        
        
    }
}