<?php

use Illuminate\Database\Seeder;

class MenuRolesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_roles')->delete();
        
        \DB::table('menu_roles')->insert(array (
            0 => 
            array (
                'menu_id' => 1,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-11 07:22:01',
                'updated_at' => '2020-06-29 08:32:21',
            ),
            1 => 
            array (
                'menu_id' => 1,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            2 => 
            array (
                'menu_id' => 2,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-03-09 20:41:09',
                'updated_at' => '2020-06-29 08:32:21',
            ),
            3 => 
            array (
                'menu_id' => 2,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            4 => 
            array (
                'menu_id' => 3,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-09 20:41:09',
                'updated_at' => '2020-06-29 08:32:21',
            ),
            5 => 
            array (
                'menu_id' => 3,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 06:35:08',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            6 => 
            array (
                'menu_id' => 4,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-11 07:22:01',
                'updated_at' => '2020-06-29 08:32:21',
            ),
            7 => 
            array (
                'menu_id' => 4,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            8 => 
            array (
                'menu_id' => 10,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-09 20:41:09',
                'updated_at' => '2020-06-29 08:32:21',
            ),
            9 => 
            array (
                'menu_id' => 10,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            10 => 
            array (
                'menu_id' => 10,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            11 => 
            array (
                'menu_id' => 10,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            12 => 
            array (
                'menu_id' => 10,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            13 => 
            array (
                'menu_id' => 10,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            14 => 
            array (
                'menu_id' => 10,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            15 => 
            array (
                'menu_id' => 12,
                'role_id' => 4,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-11 07:22:01',
                'updated_at' => '2020-06-29 08:32:21',
            ),
            16 => 
            array (
                'menu_id' => 12,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-10 08:47:09',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            17 => 
            array (
                'menu_id' => 14,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            18 => 
            array (
                'menu_id' => 15,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            19 => 
            array (
                'menu_id' => 16,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            20 => 
            array (
                'menu_id' => 17,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-12 10:51:08',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            21 => 
            array (
                'menu_id' => 18,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-13 11:00:15',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            22 => 
            array (
                'menu_id' => 19,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-21 11:00:09',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            23 => 
            array (
                'menu_id' => 20,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-03-23 20:07:31',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            24 => 
            array (
                'menu_id' => 20,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            25 => 
            array (
                'menu_id' => 20,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            26 => 
            array (
                'menu_id' => 20,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            27 => 
            array (
                'menu_id' => 20,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            28 => 
            array (
                'menu_id' => 20,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            29 => 
            array (
                'menu_id' => 21,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-03-30 15:15:11',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            30 => 
            array (
                'menu_id' => 22,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-02 06:17:56',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            31 => 
            array (
                'menu_id' => 23,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            32 => 
            array (
                'menu_id' => 23,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            33 => 
            array (
                'menu_id' => 23,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            34 => 
            array (
                'menu_id' => 23,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            35 => 
            array (
                'menu_id' => 23,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            36 => 
            array (
                'menu_id' => 23,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            37 => 
            array (
                'menu_id' => 24,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            38 => 
            array (
                'menu_id' => 24,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            39 => 
            array (
                'menu_id' => 24,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            40 => 
            array (
                'menu_id' => 24,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            41 => 
            array (
                'menu_id' => 24,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            42 => 
            array (
                'menu_id' => 25,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            43 => 
            array (
                'menu_id' => 25,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            44 => 
            array (
                'menu_id' => 26,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 14:57:31',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            45 => 
            array (
                'menu_id' => 26,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 1,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            46 => 
            array (
                'menu_id' => 27,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 15:05:48',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            47 => 
            array (
                'menu_id' => 27,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:48:36',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            48 => 
            array (
                'menu_id' => 27,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            49 => 
            array (
                'menu_id' => 27,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            50 => 
            array (
                'menu_id' => 27,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            51 => 
            array (
                'menu_id' => 27,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            52 => 
            array (
                'menu_id' => 28,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 15:05:49',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            53 => 
            array (
                'menu_id' => 28,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:48:36',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            54 => 
            array (
                'menu_id' => 28,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            55 => 
            array (
                'menu_id' => 28,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            56 => 
            array (
                'menu_id' => 28,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            57 => 
            array (
                'menu_id' => 28,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 1,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 1,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            58 => 
            array (
                'menu_id' => 29,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-04-24 15:05:49',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            59 => 
            array (
                'menu_id' => 29,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            60 => 
            array (
                'menu_id' => 29,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            61 => 
            array (
                'menu_id' => 29,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            62 => 
            array (
                'menu_id' => 29,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            63 => 
            array (
                'menu_id' => 30,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-05 16:35:38',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            64 => 
            array (
                'menu_id' => 30,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            65 => 
            array (
                'menu_id' => 30,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            66 => 
            array (
                'menu_id' => 30,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            67 => 
            array (
                'menu_id' => 30,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            68 => 
            array (
                'menu_id' => 31,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 1,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-08 06:42:02',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            69 => 
            array (
                'menu_id' => 33,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 1,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            70 => 
            array (
                'menu_id' => 33,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            71 => 
            array (
                'menu_id' => 33,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            72 => 
            array (
                'menu_id' => 33,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            73 => 
            array (
                'menu_id' => 33,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            74 => 
            array (
                'menu_id' => 33,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            75 => 
            array (
                'menu_id' => 34,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            76 => 
            array (
                'menu_id' => 34,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:48:36',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            77 => 
            array (
                'menu_id' => 34,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            78 => 
            array (
                'menu_id' => 34,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            79 => 
            array (
                'menu_id' => 35,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            80 => 
            array (
                'menu_id' => 35,
                'role_id' => 10,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:34:06',
                'updated_at' => '2020-06-29 08:48:36',
            ),
            81 => 
            array (
                'menu_id' => 35,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            82 => 
            array (
                'menu_id' => 35,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            83 => 
            array (
                'menu_id' => 35,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            84 => 
            array (
                'menu_id' => 35,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            85 => 
            array (
                'menu_id' => 36,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-05-30 16:52:43',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            86 => 
            array (
                'menu_id' => 36,
                'role_id' => 11,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:37:14',
                'updated_at' => '2020-06-29 19:05:04',
            ),
            87 => 
            array (
                'menu_id' => 36,
                'role_id' => 12,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:41:40',
                'updated_at' => '2020-06-29 19:05:20',
            ),
            88 => 
            array (
                'menu_id' => 36,
                'role_id' => 13,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:43:58',
                'updated_at' => '2020-06-30 04:34:10',
            ),
            89 => 
            array (
                'menu_id' => 36,
                'role_id' => 14,
                'authority_read' => 1,
                'authority_create' => 0,
                'authority_update' => 0,
                'authority_delete' => 0,
                'authority_import' => 0,
                'authority_export' => 1,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-06-29 08:46:38',
                'updated_at' => '2020-06-30 04:50:06',
            ),
            90 => 
            array (
                'menu_id' => 37,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-12 13:25:21',
                'updated_at' => '2020-07-12 13:25:21',
            ),
            91 => 
            array (
                'menu_id' => 38,
                'role_id' => 5,
                'authority_read' => 1,
                'authority_create' => 1,
                'authority_update' => 0,
                'authority_delete' => 1,
                'authority_import' => 0,
                'authority_export' => 0,
                'authority_approve' => 0,
                'authority_disposition' => 0,
                'authority_data' => NULL,
                'created_at' => '2020-07-12 13:25:21',
                'updated_at' => '2020-07-12 13:25:21',
            ),
        ));
        
        
    }
}